# 使用目标求值后的 include 视图编译面向作者的契约。
include("${LAYER_COMPILE_MANIFEST}")
set(compile_flags ${layer_cxx_flags})
foreach(directory IN LISTS capability_nodes_includes)
  list(APPEND compile_flags "-I${directory}")
endforeach()
foreach(definition IN LISTS capability_nodes_definitions)
  list(APPEND compile_flags "-D${definition}")
endforeach()

file(GLOB fixtures "${FIXTURE_DIR}/*.cpp")
set(valid_fixtures)
set(invalid_fixtures)
foreach(fixture IN LISTS fixtures)
  file(STRINGS "${fixture}" expectation LIMIT_COUNT 1)
  if(expectation STREQUAL "// expect-ok")
    list(APPEND valid_fixtures "${fixture}")
  elseif(expectation MATCHES "^// expect-error: .+")
    list(APPEND invalid_fixtures "${fixture}")
  else()
    message(FATAL_ERROR "Missing compile expectation in ${fixture}")
  endif()
endforeach()
list(LENGTH valid_fixtures valid_count)
list(LENGTH invalid_fixtures invalid_count)
if(valid_count LESS 1 OR invalid_count LESS 8)
  message(FATAL_ERROR "Signature fixtures incomplete: ${valid_count} valid, ${invalid_count} invalid; require at least 1 and 8")
endif()

foreach(fixture IN LISTS valid_fixtures invalid_fixtures)
  file(STRINGS "${fixture}" expectation LIMIT_COUNT 1)
  execute_process(
    COMMAND "${CMAKE_COMMAND}" -E env LC_ALL=C
            "${layer_cxx}" -std=c++17 -fsyntax-only -fdiagnostics-color=never
            ${compile_flags} "${fixture}"
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(expectation STREQUAL "// expect-ok")
    if(NOT status EQUAL 0)
      message(FATAL_ERROR "Valid signature fixture ${fixture} failed:\n${output}\n${error}")
    endif()
  else()
    string(REGEX REPLACE "^// expect-error: " "" expected "${expectation}")
    string(REGEX MATCH "[^\n]*error:[^\n]*" first_error "${output}\n${error}")
    string(FIND "${first_error}" "${expected}" diagnostic_position)
    if(status EQUAL 0 OR diagnostic_position EQUAL -1)
      message(FATAL_ERROR "Fixture ${fixture} must fail first with '${expected}':\n${output}\n${error}")
    endif()
  endif()
endforeach()

# 提取规范签名前先拼接相邻的 C++ 字符串字面量。
# 本脚本自身不维护重复的签名列表。
file(READ "${FUNCTION_NODE_HEADER}" contract_text)
string(REGEX REPLACE "\"[ \t\r\n]+\"" "" contract_text "${contract_text}")
string(REGEX MATCHALL "NodeResult<OutputBatch> Run\\([^)]*\\)"
  signatures "${contract_text}")
list(REMOVE_DUPLICATES signatures)
list(LENGTH signatures signature_count)
if(signature_count LESS 1)
  message(FATAL_ERROR "No canonical Run signature found in ${FUNCTION_NODE_HEADER}")
endif()
file(READ "${CONCEPTS_DOC}" concepts_text)
foreach(signature IN LISTS signatures)
  string(FIND "${concepts_text}" "${signature}" documented_position)
  if(documented_position EQUAL -1)
    message(FATAL_ERROR "Signature quick reference lacks: ${signature}")
  endif()
endforeach()
message(STATUS "Signature contracts passed: ${valid_count} valid, ${invalid_count} invalid, ${signature_count} documented signatures")
