# Invoked by the existing LayerGuardTest with generated, evaluated target paths.
include("${LAYER_COMPILE_MANIFEST}")
file(MAKE_DIRECTORY "${layer_test_root}")

function(check_header layer header allowed)
  string(MAKE_C_IDENTIFIER "${layer}_${header}" case_name)
  set(source "${layer_test_root}/${case_name}.cpp")
  file(WRITE "${source}" "#include <${header}>\n")
  set(include_flags)
  foreach(directory IN LISTS ${layer}_includes)
    list(APPEND include_flags "-I${directory}")
  endforeach()
  execute_process(COMMAND "${CMAKE_COMMAND}" -E env LC_ALL=C
      "${layer_cxx}" -std=c++17 -fsyntax-only
      ${layer_cxx_flags}
      ${include_flags} "${source}"
      RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(allowed AND NOT status EQUAL 0)
    message(FATAL_ERROR "${layer} cannot compile allowed header ${header}:\n${error}")
  elseif(NOT allowed)
    if(status EQUAL 0)
      message(FATAL_ERROR "${layer} can compile forbidden header ${header}")
    endif()
    # A failing transitive include is not proof that the named boundary held.
    string(FIND "${error}" "${header}: No such file" gcc_missing)
    string(FIND "${error}" "'${header}' file not found" clang_missing)
    if(gcc_missing EQUAL -1 AND clang_missing EQUAL -1)
      message(FATAL_ERROR "${layer}/${header} failed for an unrelated reason:\n${error}")
    endif()
  endif()
endfunction()

check_header(model_execution engine/model_interface.h TRUE)
check_header(model_execution engine/models/bge_common/bert_wordpiece_tokenizer.h TRUE)
check_header(capability_nodes nodes/node_base.h TRUE)
check_header(capability_nodes core/validated_node_plan.h TRUE)
check_header(capability_nodes engine/text/utf8.h TRUE)
check_header(orchestration core/pipeline.h TRUE)
check_header(integration adapter/operator/operator_config_resolver.h TRUE)
check_header(integration adapter/operator_biz_bridge.h TRUE)
check_header(capability_nodes core/node_definition.h TRUE)
check_header(capability_nodes core/port_definition.h TRUE)
check_header(public edgeflow/c_api.h TRUE)
check_header(public edgeflow/c_api.hpp TRUE)
check_header(public edgeflow/operator/interface.h TRUE)
check_header(public company_alg_interface.h TRUE)
check_header(public company_alg_cpp.hpp TRUE)
check_header(public operator/operator_interface.h TRUE)
check_header(public adapter/biz_adapter_interface.h FALSE)
check_header(public adapter/shared_algorithm_runtime.h FALSE)
check_header(public adapter/operator/operator_config_resolver.h FALSE)
check_header(public core/pipeline.h FALSE)
check_header(public nodes/node_base.h FALSE)
check_header(public engine/tensor.h FALSE)
check_header(extension adapter/biz_adapter_interface.h TRUE)
check_header(extension adapter/operator_biz_bridge.h TRUE)
check_header(extension nodes/node_base.h TRUE)
check_header(extension engine/model_interface.h TRUE)
check_header(extension adapter/shared_algorithm_runtime.h FALSE)
check_header(extension adapter/operator/operator_biz_bridge_registry.h FALSE)
check_header(extension adapter/operator/operator_output_pool.h FALSE)

foreach(header alg_types.h error_codes.h operator_data_types.h operator_types.h)
  check_header(public platform_mock/${header} TRUE)
  check_header(integration platform_mock/${header} TRUE)
  foreach(layer model_execution capability_nodes orchestration)
    check_header(${layer} platform_mock/${header} FALSE)
  endforeach()
endforeach()

foreach(layer model_execution capability_nodes orchestration)
  check_header(${layer} adapter/biz_adapter_interface.h FALSE)
  check_header(${layer} adapter/operator/operator_config_resolver.h FALSE)
  check_header(${layer} edgeflow/c_api.h FALSE)
endforeach()
foreach(layer model_execution capability_nodes orchestration integration)
  check_header(${layer} src/adapter/operator/operator_config_resolver.h FALSE)
  check_header(${layer} include/edgeflow/c_api.h FALSE)
endforeach()
check_header(model_execution core/alg_context.h FALSE)
check_header(model_execution nodes/node_base.h FALSE)
check_header(capability_nodes core/pipeline_validator.h FALSE)
check_header(orchestration nodes/node_base.h FALSE)
foreach(layer capability_nodes orchestration integration)
  check_header(${layer} engine/models/bge_common/bert_wordpiece_tokenizer.h FALSE)
  check_header(${layer} engine/backends/onnxruntime/onnxruntime_backend.h FALSE)
endforeach()

# Verify the actual CMake module through an incremental, dependency-free fixture.
# The normal generator is reused, including when the parent uses multi-config.
set(fixture "${layer_test_root}/lifecycle")
if(DEFINED LAYER_LIFECYCLE_GENERATOR)
  set(layer_generator "${LAYER_LIFECYCLE_GENERATOR}")
endif()
file(REMOVE_RECURSE "${fixture}")
file(MAKE_DIRECTORY "${fixture}/cmake_ext" "${fixture}/src/engine/text")
file(COPY "${layer_source_dir}/include" DESTINATION "${fixture}")
file(COPY "${layer_source_dir}/cmake_ext/node_core_contracts.txt" DESTINATION "${fixture}/cmake_ext")
file(COPY "${layer_source_dir}/src/engine/text/utf8.h" DESTINATION "${fixture}/src/engine/text")
file(WRITE "${fixture}/CMakeLists.txt"
  "cmake_minimum_required(VERSION 3.16)\nproject(HeaderViewLifecycle NONE)\ninclude(\"${layer_source_dir}/cmake_ext/LayerHeaderViews.cmake\")\n")
function(run_fixture)
  execute_process(COMMAND "${CMAKE_COMMAND}" ${ARGN}
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(NOT status EQUAL 0)
    message(FATAL_ERROR "Header view lifecycle failed: ${output}\n${error}")
  endif()
endfunction()
run_fixture(-S "${fixture}" -B "${fixture}/build" -G "${layer_generator}")
set(fixture_header "${fixture}/include/contracts/lifecycle_probe.h")
set(fixture_view "${fixture}/build/layer_includes/contracts/contracts/lifecycle_probe.h")
file(WRITE "${fixture_header}" "// first revision\n")
run_fixture(--build "${fixture}/build")
if(NOT EXISTS "${fixture_view}")
  message(FATAL_ERROR "A newly added contract header did not enter its include view")
endif()
file(WRITE "${fixture_header}" "// second revision\n")
run_fixture(--build "${fixture}/build")
file(READ "${fixture_view}" visible_content)
if(NOT visible_content STREQUAL "// second revision\n")
  message(FATAL_ERROR "The include view retained stale header contents")
endif()
file(REMOVE "${fixture_header}")
run_fixture(--build "${fixture}/build")
if(EXISTS "${fixture_view}" OR IS_SYMLINK "${fixture_view}")
  message(FATAL_ERROR "A removed header left a stale file in its include view")
endif()
message(STATUS "Layer target compiler include visibility checks passed.")
