#include "core/pipeline_validator.h"

#include <algorithm>
#include <functional>
#include <queue>
#include <unordered_map>
#include <unordered_set>

#include "contracts/config_schema_validation.h"
#include "contracts/json_pointer.h"
#include "contracts/path_utils.h"
#include "core/node_registry.h"
#include "core/pipeline_catalog.h"
#include "core/pipeline_config.h"
#include "engine/backend_registry.h"
#include "engine/model_registry.h"
#include "name_suggestions.h"
#include "pipeline_config_structure.h"

namespace llm_edgeflow {
namespace {

void Add(ValidationReport* report, DiagnosticCode code, std::string path,
         std::string message, std::string node_id = {}, std::string port = {},
         std::vector<std::string> related = {},
         std::vector<std::string> suggestions = {}) {
  report->diagnostics.push_back({code, std::move(path), std::move(message),
                                 "error", std::move(node_id), std::move(port),
                                 std::move(related), std::move(suggestions),
                                 std::nullopt, nlohmann::json::object()});
}

nlohmann::json PortContractFacts(const PortContract& port) {
  return {{"type_id", port.type_id},
          {"cardinality", port.cardinality},
          {"provenance_policy", port.provenance_policy},
          {"lifetime", port.lifetime}};
}

void AddPortFlowDiagnostic(
    ValidationReport* report, DiagnosticCode code, const std::string& path,
    std::string message, const std::string& producer_id,
    const std::string& consumer_id, PortDirection location,
    const std::string& logical_port, const std::string& bound_key,
    const PortContract& producer, const PortContract& consumer) {
  // Node 输入诊断归属消费者，边界诊断归属生产者。
  // 保留这些位置和相关 Node ID。
  const bool boundary = location == PortDirection::kOutput;
  Add(report, code, path, std::move(message),
      boundary ? producer_id : consumer_id, logical_port,
      {boundary ? consumer_id : producer_id});
  report->diagnostics.back().facts = {
      {"producer_id", producer_id},
      {"consumer_id", consumer_id},
      {"bound_key", bound_key},
      {"actual", PortContractFacts(producer)},
      {"expected", PortContractFacts(consumer)}};
}

NodePortDefinition EffectivePortDefinition(
    const NodePortDefinition& declared, const NodeDefinition& node_definition,
    const nlohmann::json& node_config) {
  NodePortDefinition effective = declared;
  if (declared.lifetime_config_field.empty()) return effective;

  const auto& field_name = declared.lifetime_config_field;
  if (node_config.contains(field_name) && node_config[field_name].is_string()) {
    effective.lifetime = node_config[field_name].get<std::string>();
    return effective;
  }
  auto field =
      std::find_if(node_definition.config_fields.begin(),
                   node_definition.config_fields.end(),
                   [&](const auto& item) { return item.name == field_name; });
  if (field != node_definition.config_fields.end() &&
      field->default_value.is_string()) {
    effective.lifetime = field->default_value.get<std::string>();
  }
  return effective;
}

// 一个请求在某 Blackboard 键下的条目数。Node 的 cardinality 描述 Node 自身的
// 关系：输入表示条目的消费方式 ("1:1" 逐条，"N:1" 按请求分组，"N:M" 任意)，
// 且接受任意形状；输出表示产出条目与逐条输入之间的关系。形状沿 DAG 推导，
// 只在关键处检查：要求每请求一个条目的边界，以及必须两两配对的逐条输入。
struct KeyShape {
  enum class Kind { kUnknown, kPerRequest, kMulti };
  Kind kind = Kind::kUnknown;
  std::string origin;  // 生成 kMulti 形状条目的扇出来源。

  static KeyShape Unknown() { return {}; }
  static KeyShape PerRequest() { return {Kind::kPerRequest, {}}; }
  static KeyShape Multi(std::string origin) {
    return {Kind::kMulti, std::move(origin)};
  }
  bool Known() const { return kind != Kind::kUnknown; }
  bool operator==(const KeyShape& other) const {
    return kind == other.kind && origin == other.origin;
  }
};

std::string DescribeShape(const KeyShape& shape) {
  switch (shape.kind) {
    case KeyShape::Kind::kPerRequest:
      return "one item per request";
    case KeyShape::Kind::kMulti:
      return "zero or more items per request generated by '" + shape.origin +
             "'";
    case KeyShape::Kind::kUnknown:
      break;
  }
  return "an unknown number of items per request";
}

nlohmann::json ShapeFacts(const KeyShape& shape) {
  switch (shape.kind) {
    case KeyShape::Kind::kPerRequest:
      return {{"kind", "per_request"}};
    case KeyShape::Kind::kMulti:
      return {{"kind", "multi"}, {"origin", shape.origin}};
    case KeyShape::Kind::kUnknown:
      break;
  }
  return {{"kind", "unknown"}};
}

// Biz 和 IO 边界端口按请求计数："1:1" 恰为一个条目，
// 其他声明均为归属该请求的集合。
KeyShape BoundaryShape(const PortContract& port, std::string origin) {
  return port.cardinality == "1:1" ? KeyShape::PerRequest()
                                   : KeyShape::Multi(std::move(origin));
}

KeyShape NodeOutputShape(const PortContract& output, const KeyShape& item_shape,
                         std::string origin) {
  if (output.cardinality == "1:1") return item_shape;
  if (output.cardinality == "1:N") return KeyShape::Multi(std::move(origin));
  if (output.cardinality == "N:1") return KeyShape::PerRequest();
  return KeyShape::Unknown();
}

void ValidateBoundaryShape(
    const KeyShape& produced, const PortContract& producer,
    const PortContract& consumer, const std::string& path,
    const std::string& producer_id, const std::string& consumer_id,
    const std::string& bound_key, ValidationReport* report) {
  if (consumer.cardinality != "1:1" || produced.kind != KeyShape::Kind::kMulti)
    return;
  AddPortFlowDiagnostic(report, DiagnosticCode::kPortCardinalityMismatch, path,
                        "Port cardinality mismatch: '" + bound_key +
                            "' requires one item per request but receives " +
                            DescribeShape(produced),
                        producer_id, consumer_id, PortDirection::kOutput,
                        bound_key, bound_key, producer, consumer);
  auto& facts = report->diagnostics.back().facts;
  facts["actual_shape"] = ShapeFacts(produced);
  facts["expected_shape"] = ShapeFacts(KeyShape::PerRequest());
}

bool ProvenanceCompatible(const std::string& producer,
                          const std::string& consumer) {
  if (consumer == "preserve" || consumer == "aggregate") return true;
  return producer == consumer;
}

int LifetimeRank(const std::string& lifetime) {
  if (lifetime == "request") return 0;
  if (lifetime == "session") return 1;
  if (lifetime == "global") return 2;
  return -1;
}

bool TraversesParent(const std::filesystem::path& path) {
  // 即使宿主文件系统把反斜杠视为普通文件名字符，
  // 仍保留可移植的 Windows 前导父目录检查。
  return HasParentPathComponent(path) || path.string().rfind("..\\", 0) == 0;
}

bool LifetimeCompatible(const std::string& producer,
                        const std::string& consumer) {
  return LifetimeRank(producer) >= LifetimeRank(consumer);
}

void ValidatePortFlowContract(
    const PortContract& producer, const PortContract& consumer,
    const std::string& path, const std::string& producer_id,
    const std::string& consumer_id, PortDirection location,
    const std::string& logical_port, const std::string& bound_key,
    ValidationReport* report) {
  if (!ProvenanceCompatible(producer.provenance_policy,
                            consumer.provenance_policy)) {
    AddPortFlowDiagnostic(report, DiagnosticCode::kPortProvenanceMismatch, path,
                          "Port provenance mismatch: producer policy '" +
                              producer.provenance_policy +
                              "' cannot satisfy consumer policy '" +
                              consumer.provenance_policy + "'",
                          producer_id, consumer_id, location, logical_port,
                          bound_key, producer, consumer);
  }
  if (!LifetimeCompatible(producer.lifetime, consumer.lifetime)) {
    AddPortFlowDiagnostic(
        report, DiagnosticCode::kPortLifetimeMismatch, path,
        "Port lifetime mismatch: producer lifetime '" + producer.lifetime +
            "' is shorter than consumer lifetime '" + consumer.lifetime + "'",
        producer_id, consumer_id, location, logical_port, bound_key, producer,
        consumer);
  }
}

}  // namespace

bool ValidateAndNormalizeConfig(
    const std::vector<ConfigFieldDefinition>& schema,
    const nlohmann::json& input, nlohmann::json* normalized,
    std::vector<ValidationDiagnostic>* diagnostics,
    const std::string& base_pointer, DiagnosticCode unknown_field_code) {
  std::vector<ConfigFieldValidationError> field_errors;
  bool ok =
      ValidateAndNormalizeFields(schema, input, normalized, &field_errors);
  if (!ok && diagnostics) {
    for (const auto& err : field_errors) {
      ValidationDiagnostic diag;
      diag.path = err.kind == ConfigFieldErrorKind::kNotAnObject
                      ? base_pointer
                      : base_pointer + "/" + err.field_name;
      diag.message = err.message;
      switch (err.kind) {
        case ConfigFieldErrorKind::kNotAnObject:
          diag.code = DiagnosticCode::kConfigFieldType;
          break;
        case ConfigFieldErrorKind::kUnknownField:
          diag.code = unknown_field_code;
          for (const auto& field : schema) {
            diag.suggestions.push_back(field.name);
          }
          diag.suggestions =
              RankByEditDistance(err.field_name, std::move(diag.suggestions));
          break;
        case ConfigFieldErrorKind::kMissingField:
          diag.code = DiagnosticCode::kMissingConfigField;
          break;
        case ConfigFieldErrorKind::kTypeMismatch:
          diag.code = DiagnosticCode::kConfigFieldType;
          break;
        case ConfigFieldErrorKind::kOutOfRange:
        case ConfigFieldErrorKind::kNonFinite:
          diag.code = DiagnosticCode::kConfigFieldRange;
          break;
        case ConfigFieldErrorKind::kInvalidEnum:
          diag.code = DiagnosticCode::kConfigFieldEnum;
          break;
      }
      diag.severity = "error";
      diagnostics->push_back(std::move(diag));
    }
  }
  return ok;
}

namespace {

nlohmann::json ValidateConfigFields(
    const std::vector<ConfigFieldDefinition>& definitions,
    const nlohmann::json& config, const std::string& path_prefix,
    const std::string& subject_id, ValidationReport* report,
    bool* out_valid = nullptr) {
  std::vector<ValidationDiagnostic> diags;
  nlohmann::json normalized = nlohmann::json::object();
  if (config.is_object()) {
    for (const auto& field : definitions) {
      if (config.contains(field.name)) {
        normalized[field.name] = config[field.name];
      } else if (!field.default_value.is_null()) {
        normalized[field.name] = field.default_value;
      }
    }
  }

  nlohmann::json validated;
  bool ok = ValidateAndNormalizeConfig(definitions, config, &validated, &diags,
                                       path_prefix);
  if (ok) {
    normalized = std::move(validated);
  }
  if (out_valid) *out_valid = ok;
  for (auto& d : diags) {
    d.node_id = subject_id;
    report->diagnostics.push_back(std::move(d));
  }
  return normalized;
}

bool ResolveTopology(const std::vector<ParsedNodeConfig>& nodes,
                     ValidationReport* report) {
  const bool unique_dependencies = PipelineConfigStructure()
                                       .at("properties")
                                       .at("pipeline")
                                       .at("items")
                                       .at("properties")
                                       .at("depends_on")
                                       .at("uniqueItems")
                                       .get<bool>();
  std::unordered_map<std::string, size_t> index;
  std::unordered_map<std::string, int> degrees;
  std::unordered_map<std::string, std::vector<std::string>> children;
  for (size_t i = 0; i < nodes.size(); ++i) {
    index[nodes[i].id] = i;
    degrees[nodes[i].id] = 0;
  }
  bool invalid_reference = false;
  for (const auto& node : nodes) {
    std::unordered_set<std::string> seen;
    for (size_t d = 0; d < node.depends_on.size(); ++d) {
      const auto& dep = node.depends_on[d];
      std::string path = "/pipeline/" + std::to_string(node.source_index) +
                         "/depends_on/" + std::to_string(d);
      if (dep == node.id) {
        Add(report, DiagnosticCode::kDagCycle, path,
            "Node cannot depend on itself", node.id, {}, {dep});
        invalid_reference = true;
      } else if (index.find(dep) == index.end()) {
        Add(report, DiagnosticCode::kInvalidDependency, path,
            "Dependency references an unknown node: " + dep, node.id, {},
            {dep});
        invalid_reference = true;
      } else if (unique_dependencies && !seen.insert(dep).second) {
        Add(report, DiagnosticCode::kDuplicateDependency, path,
            "Dependency is declared more than once: " + dep, node.id, {},
            {dep});
        invalid_reference = true;
      } else {
        ++degrees[node.id];
        children[dep].push_back(node.id);
      }
    }
  }
  std::vector<std::string> current;
  for (const auto& node : nodes) {
    if (degrees[node.id] == 0) current.push_back(node.id);
  }
  size_t resolved = 0;
  while (!current.empty()) {
    report->topological_layers.push_back(current);
    std::vector<std::string> next;
    for (const auto& id : current) {
      report->topological_order.push_back(id);
      ++resolved;
      for (const auto& child : children[id]) {
        if (--degrees[child] == 0) next.push_back(child);
      }
    }
    current = std::move(next);
  }
  if (resolved != nodes.size()) {
    Add(report, DiagnosticCode::kDagCycle, "/pipeline",
        "Cyclic dependency detected in pipeline");
    return false;
  }
  return !invalid_reference;
}

ValidatedPipelinePlan ValidateAndPlanInternal(
    const nlohmann::json& root, const PipelineCatalogSnapshot& catalog,
    const PipelineIoBoundary* io_boundary = nullptr) {
  ValidatedPipelinePlan plan;
  ValidationReport& report = plan.report;

  auto finish_plan = [&](ValidatedPipelinePlan& p) {
    p.report.ok = p.report.diagnostics.empty();
  };

  PipelineDiagnostic parse_diag;
  if (!ParsePipelineConfig(root, &plan.config, &parse_diag)) {
    Add(&report, parse_diag.code, parse_diag.path, parse_diag.message);
    finish_plan(plan);
    return plan;
  }
  const auto& parsed = plan.config;
  const auto* biz = catalog.FindBiz(parsed.biz_name);
  if (!biz) {
    Add(&report, DiagnosticCode::kUnknownBiz, "/biz_name",
        "No registered biz contract accepts pipeline name: " + parsed.biz_name);
  }
  if (catalog.node_registry_has_conflict) {
    std::string message = "Node registry contains registration conflicts";
    for (const auto& error : catalog.node_registry_errors) {
      message += ": " + error;
    }
    Add(&report, DiagnosticCode::kRegistryConflict, "/pipeline",
        std::move(message));
  }
  if (ModelRegistry::Instance().HasConflict()) {
    Add(&report, DiagnosticCode::kRegistryConflict, "/models",
        "Model registry contains registration conflicts");
  }
  if (BackendRegistry::Instance().HasConflict()) {
    Add(&report, DiagnosticCode::kRegistryConflict, "/models",
        "Backend registry contains registration conflicts");
  }

  std::unordered_set<std::string> unresolved_model_ids;
  std::unordered_set<std::string> unresolved_output_keys;
  std::unordered_set<std::string> reported_missing_outputs;
  std::unordered_map<std::string, std::string> model_capabilities;
  std::unordered_map<std::string, InferenceConcurrency> model_concurrency;
  for (const auto& model : parsed.models) {
    auto model_def_opt = ModelRegistry::Instance().Find(model.model_type);
    if (!model_def_opt) {
      unresolved_model_ids.insert(model.model_id);
      std::vector<std::string> model_types;
      for (const auto& def : PipelineCatalog::Models())
        model_types.push_back(def.model_type);
      Add(&report, DiagnosticCode::kUnknownModelType,
          "/models/" + std::to_string(model.source_index) + "/model_type",
          "Unknown model_type: " + model.model_type, {}, {}, {},
          NearestNames(model.model_type, std::move(model_types)));
    } else {
      model_capabilities[model.model_id] = model_def_opt->capability;
    }

    auto backend_def_opt = BackendRegistry::Instance().Find(model.backend);
    if (!backend_def_opt) {
      std::vector<std::string> backends;
      for (const auto& def : PipelineCatalog::Backends())
        backends.push_back(def.backend_type);
      Add(&report, DiagnosticCode::kUnknownBackend,
          "/models/" + std::to_string(model.source_index) + "/backend",
          "Unknown backend: " + model.backend, {}, {}, {},
          NearestNames(model.backend, std::move(backends)));
    }

    if (model_def_opt && backend_def_opt) {
      const auto& supported_protocols = backend_def_opt->supported_protocols;
      bool protocol_supported =
          std::find(supported_protocols.begin(), supported_protocols.end(),
                    model_def_opt->required_protocol) !=
          supported_protocols.end();
      if (!protocol_supported) {
        Add(&report, DiagnosticCode::kBackendProtocolMismatch,
            "/models/" + std::to_string(model.source_index) + "/backend",
            "Backend '" + model.backend +
                "' does not support required protocol '" +
                std::string(
                    ExecutionProtocolName(model_def_opt->required_protocol)) +
                "' for model '" + model.model_type + "'");
      }

      nlohmann::json normalized_mcfg = nlohmann::json::object();
      std::vector<ValidationDiagnostic> mcfg_diags;
      const bool model_fields_valid = ValidateAndNormalizeConfig(
          model_def_opt->config_fields, model.model_config, &normalized_mcfg,
          &mcfg_diags,
          "/models/" + std::to_string(model.source_index) + "/model_config",
          DiagnosticCode::kUnknownModelConfigField);
      for (auto& d : mcfg_diags) {
        report.diagnostics.push_back(std::move(d));
      }

      if (model_fields_valid && model_def_opt->validate_config) {
        const std::string path =
            "/models/" + std::to_string(model.source_index) + "/model_config";
        std::string diagnostic;
        try {
          if (!model_def_opt->validate_config(normalized_mcfg, &diagnostic)) {
            Add(&report, DiagnosticCode::kInvalidCombination, path,
                diagnostic.empty() ? "Invalid model configuration"
                                   : diagnostic);
          }
        } catch (const std::exception& e) {
          Add(&report, DiagnosticCode::kInvalidCombination, path, e.what());
        } catch (...) {
          Add(&report, DiagnosticCode::kInvalidCombination, path,
              "Model configuration validator threw an unknown exception");
        }
      }

      nlohmann::json normalized_bcfg = nlohmann::json::object();
      std::vector<ValidationDiagnostic> bcfg_diags;
      const bool backend_fields_valid = ValidateAndNormalizeConfig(
          backend_def_opt->config_fields, model.backend_config,
          &normalized_bcfg, &bcfg_diags,
          "/models/" + std::to_string(model.source_index) + "/backend_config",
          DiagnosticCode::kUnknownBackendConfigField);
      for (auto& d : bcfg_diags) {
        report.diagnostics.push_back(std::move(d));
      }

      if (backend_fields_valid && backend_def_opt->validate_config) {
        const std::string path =
            "/models/" + std::to_string(model.source_index) + "/backend_config";
        std::string diagnostic;
        try {
          if (!backend_def_opt->validate_config(normalized_bcfg, &diagnostic)) {
            Add(&report, DiagnosticCode::kInvalidCombination, path,
                diagnostic.empty() ? "Invalid backend configuration"
                                   : diagnostic);
          }
        } catch (const std::exception& e) {
          Add(&report, DiagnosticCode::kInvalidCombination, path, e.what());
        } catch (...) {
          Add(&report, DiagnosticCode::kInvalidCombination, path,
              "Backend configuration validator threw an unknown exception");
        }
      }

      // 流程编排层只做与环境无关的词法路径检查。
      // 部署根目录由接入适配层在运行时校验前解析。
      const auto normalized_path =
          std::filesystem::path(model.model_path).lexically_normal();
      if (!normalized_path.is_absolute() && TraversesParent(normalized_path)) {
        Add(&report, DiagnosticCode::kFieldRange,
            "/models/" + std::to_string(model.source_index) + "/model_path",
            "Model path cannot traverse outside model root directory: " +
                model.model_path);
      }
      InferenceConcurrency effective_concurrency =
          (model_def_opt->concurrency == InferenceConcurrency::kSerialized ||
           backend_def_opt->concurrency == InferenceConcurrency::kSerialized)
              ? InferenceConcurrency::kSerialized
              : InferenceConcurrency::kConcurrent;

      model_concurrency[model.model_id] = effective_concurrency;

      ValidatedModelPlan model_plan;
      model_plan.model_id = model.model_id;
      model_plan.capability = model_def_opt->capability;
      model_plan.model_type = model.model_type;
      model_plan.backend = model.backend;
      model_plan.resolved_model_path = normalized_path.string();
      model_plan.normalized_model_config = std::move(normalized_mcfg);
      model_plan.normalized_backend_config = std::move(normalized_bcfg);
      model_plan.protocol = model_def_opt->required_protocol;
      model_plan.effective_concurrency = effective_concurrency;
      model_plan.source_index = model.source_index;
      plan.models.push_back(std::move(model_plan));
    }
  }

  const auto& nodes = parsed.nodes;
  std::unordered_map<std::string, const ParsedNodeConfig*> node_by_id;
  std::unordered_map<std::string, const NodeDefinition*> def_by_id;
  std::unordered_map<std::string, nlohmann::json> normalized_config_by_node;
  for (const auto& node : nodes) {
    node_by_id[node.id] = &node;
    const auto* definition = catalog.FindNode(node.node_type);
    if (!definition) {
      std::vector<std::string> node_types;
      for (const auto& def : catalog.nodes) node_types.push_back(def.node_type);
      Add(&report, DiagnosticCode::kUnknownNodeType,
          "/pipeline/" + std::to_string(node.source_index) + "/node_type",
          "Unknown node_type or missing catalog definition: " + node.node_type,
          node.id, {}, {}, NearestNames(node.node_type, std::move(node_types)));
      for (const auto& output : node.ports.outputs)
        unresolved_output_keys.insert(output.second);
      continue;
    }
    def_by_id[node.id] = definition;

    if (biz && !definition->biz_names.empty() &&
        std::find(definition->biz_names.begin(), definition->biz_names.end(),
                  parsed.biz_name) == definition->biz_names.end()) {
      Add(&report, DiagnosticCode::kNodeBizMismatch,
          "/pipeline/" + std::to_string(node.source_index) + "/node_type",
          "Node type is not declared for biz: " + parsed.biz_name, node.id);
    }

    bool node_fields_valid = false;
    auto normalized_config = ValidateConfigFields(
        definition->config_fields, node.config,
        "/pipeline/" + std::to_string(node.source_index) + "/config", node.id,
        &report, &node_fields_valid);
    if (node_fields_valid && definition->validate_config) {
      std::unordered_set<std::string> connected;
      for (const auto& binding : node.ports.inputs)
        connected.insert(binding.first);
      std::string diagnostic;
      try {
        if (!definition->validate_config(normalized_config, connected,
                                         &diagnostic)) {
          Add(&report, DiagnosticCode::kInvalidCombination,
              "/pipeline/" + std::to_string(node.source_index) + "/config",
              diagnostic.empty() ? "Invalid node configuration" : diagnostic,
              node.id);
        }
      } catch (const std::exception& e) {
        Add(&report, DiagnosticCode::kInvalidCombination,
            "/pipeline/" + std::to_string(node.source_index) + "/config",
            e.what(), node.id);
      } catch (...) {
        Add(&report, DiagnosticCode::kInvalidCombination,
            "/pipeline/" + std::to_string(node.source_index) + "/config",
            "Node configuration validator threw an unknown exception", node.id);
      }
    }
    normalized_config_by_node[node.id] = normalized_config;

    for (const auto& dep : definition->model_dependencies) {
      std::string model_id;
      if (normalized_config.contains(dep.config_field) &&
          normalized_config[dep.config_field].is_string()) {
        model_id = normalized_config[dep.config_field].get<std::string>();
      }
      auto capability = model_capabilities.find(model_id);
      std::string path = "/pipeline/" + std::to_string(node.source_index) +
                         "/config/" + EscapeJsonPointer(dep.config_field);
      if (model_id.empty() || capability == model_capabilities.end()) {
        if (!unresolved_model_ids.count(model_id)) {
          Add(&report, DiagnosticCode::kUnknownModelReference, path,
              "Node references an unknown model_id: " + model_id, node.id);
        }
      } else if (capability->second != dep.capability) {
        Add(&report, DiagnosticCode::kModelCapabilityMismatch, path,
            "Node requires model capability '" + dep.capability +
                "' but model provides '" + capability->second + "'",
            node.id);
      }
    }
  }

  std::unordered_map<std::string, BizPortDefinition> ingress;
  if (biz) {
    for (const auto& port : biz->ingress) ingress[port.blackboard_key] = port;
  }
  if (io_boundary) {
    std::unordered_map<std::string, BizPortDefinition> input_pub;
    for (const auto& port : io_boundary->input_published_ports) {
      input_pub[port.blackboard_key] = port;
    }
    if (biz) {
      for (const auto& req_in : biz->ingress) {
        if (!req_in.required) continue;
        auto it = input_pub.find(req_in.blackboard_key);
        if (it == input_pub.end()) {
          Add(&report, DiagnosticCode::kMissingInputProducer, "/io/input",
              "IO boundary input does not publish required biz ingress port: " +
                  req_in.blackboard_key,
              "$io_input", req_in.blackboard_key);
        } else {
          if (it->second.type_id != req_in.type_id) {
            Add(&report, DiagnosticCode::kMissingInputProducer, "/io/input",
                "IO boundary input port type mismatch for '" +
                    req_in.blackboard_key + "': expected '" + req_in.type_id +
                    "', got '" + it->second.type_id + "'",
                "$io_input", req_in.blackboard_key);
          } else {
            ValidatePortFlowContract(
                it->second, req_in, "/io/input", "$io_input", "$ingress",
                PortDirection::kOutput, req_in.blackboard_key,
                req_in.blackboard_key, &report);
            ValidateBoundaryShape(
                BoundaryShape(it->second, "$ingress." + req_in.blackboard_key),
                it->second, req_in, "/io/input", "$io_input", "$ingress",
                req_in.blackboard_key, &report);
          }
        }
      }
    }
    for (const auto& port : io_boundary->input_published_ports) {
      ingress[port.blackboard_key] = port;
    }
  }
  std::unordered_map<std::string,
                     std::vector<std::pair<std::string, PortContract>>>
      producers;
  // 先确定归属再排序。数组顺序从不决定生产者。
  for (const auto& node : nodes) {
    auto def_it = def_by_id.find(node.id);
    if (def_it == def_by_id.end()) continue;
    const auto& definition = *def_it->second;
    const auto& normalized_config = normalized_config_by_node.at(node.id);
    for (const auto& declared_output : definition.outputs) {
      const auto output = EffectivePortDefinition(declared_output, definition,
                                                  normalized_config);
      auto binding = node.ports.outputs.find(output.logical_name);
      const std::string& key = binding == node.ports.outputs.end()
                                   ? output.logical_name
                                   : binding->second;
      auto& existing = producers[key];
      std::vector<std::string> conflicts;
      if (ingress.count(key)) conflicts.push_back("$ingress");
      for (const auto& producer : existing) conflicts.push_back(producer.first);
      if (!conflicts.empty()) {
        Add(&report, DiagnosticCode::kDuplicatePortProducer,
            "/pipeline/" + std::to_string(node.source_index) + "/outputs/" +
                EscapeJsonPointer(output.logical_name),
            "Write-once Blackboard port has multiple producers: " + key,
            node.id, output.logical_name, std::move(conflicts));
      }
      existing.push_back({node.id, static_cast<const PortContract&>(output)});
    }
  }
  for (auto& node : plan.config.nodes) {
    auto def_it = def_by_id.find(node.id);
    if (def_it == def_by_id.end()) continue;
    for (const auto& input : def_it->second->inputs) {
      const auto binding = node.ports.inputs.find(input.logical_name);
      if (binding == node.ports.inputs.end()) continue;
      const auto producer = producers.find(binding->second);
      if (producer == producers.end() || producer->second.size() != 1 ||
          ingress.count(binding->second))
        continue;
      const auto& producer_id = producer->second.front().first;
      if (producer_id == node.id) {
        Add(&report, DiagnosticCode::kDagCycle,
            "/pipeline/" + std::to_string(node.source_index) + "/inputs/" +
                EscapeJsonPointer(input.logical_name),
            "Node input cannot consume its own output", node.id,
            input.logical_name, {node.id});
      } else if (std::find(node.depends_on.begin(), node.depends_on.end(),
                           producer_id) == node.depends_on.end()) {
        node.depends_on.push_back(producer_id);
      }
    }
  }

  // 仅当未注册 Node 的显式映射是唯一可能来源时，缺失生产者错误才会级联。
  // 已知生产者或入口仍允许独立进行类型/唯一性/冲突检查。
  auto has_only_unresolved_source = [&](const std::string& key) {
    auto it = producers.find(key);
    return unresolved_output_keys.count(key) &&
           (it == producers.end() || it->second.empty()) && !ingress.count(key);
  };

  const size_t pre_topology_errors = report.diagnostics.size();
  ResolveTopology(nodes, &report);
  if (report.diagnostics.size() != pre_topology_errors || !biz ||
      report.topological_order.size() != nodes.size()) {
    finish_plan(plan);
    return plan;
  }

  std::unordered_map<std::string, KeyShape> key_shapes;
  for (const auto& [key, port] : ingress) {
    key_shapes[key] = BoundaryShape(port, "$ingress." + key);
  }
  auto shape_of = [&](const std::string& key) {
    auto it = key_shapes.find(key);
    return it == key_shapes.end() ? KeyShape::Unknown() : it->second;
  };

  for (const auto& id : report.topological_order) {
    auto def_it = def_by_id.find(id);
    if (def_it == def_by_id.end()) continue;
    const auto& definition = *def_it->second;
    const auto& node = *node_by_id[id];
    const nlohmann::json& normalized_config = normalized_config_by_node.at(id);
    // 已绑定逐条输入共享的形状；没有逐条输入的 Node 每个请求只产出一个条目。
    KeyShape item_shape = KeyShape::PerRequest();
    std::string item_shape_port;
    std::string item_shape_key;

    ValidatedNodePlan node_plan;
    node_plan.node = node;
    node_plan.normalized_config = normalized_config;
    for (const auto& dep : definition.model_dependencies) {
      std::string model_id;
      if (normalized_config.contains(dep.config_field) &&
          normalized_config[dep.config_field].is_string()) {
        model_id = normalized_config[dep.config_field].get<std::string>();
      }
      ResolvedNodeModelBinding binding;
      binding.name = dep.name;
      binding.capability = dep.capability;
      binding.config_field = dep.config_field;
      binding.model_id = std::move(model_id);
      node_plan.model_bindings.push_back(std::move(binding));
    }

    // 校验未声明的输入端口映射
    for (const auto& entry : node.ports.inputs) {
      const auto& in_port = entry.first;
      bool declared = std::any_of(
          definition.inputs.begin(), definition.inputs.end(),
          [&](const auto& item) { return item.logical_name == in_port; });
      if (!declared) {
        Add(&report, DiagnosticCode::kUnknownField,
            "/pipeline/" + std::to_string(node.source_index) + "/inputs/" +
                in_port,
            "Unknown logical input port '" + in_port + "' for node type '" +
                definition.node_type + "'",
            id, in_port);
      }
    }

    // 校验未声明的输出端口映射
    for (const auto& entry : node.ports.outputs) {
      const auto& out_port = entry.first;
      bool declared = std::any_of(
          definition.outputs.begin(), definition.outputs.end(),
          [&](const auto& item) { return item.logical_name == out_port; });
      if (!declared) {
        Add(&report, DiagnosticCode::kUnknownField,
            "/pipeline/" + std::to_string(node.source_index) + "/outputs/" +
                out_port,
            "Unknown logical output port '" + out_port + "' for node type '" +
                definition.node_type + "'",
            id, out_port);
      }
    }

    std::unordered_set<std::string> bound_input_ports;
    for (const auto& declared_input : definition.inputs) {
      const auto input = EffectivePortDefinition(declared_input, definition,
                                                 normalized_config);
      const std::string input_path =
          "/pipeline/" + std::to_string(node.source_index) + "/inputs/" +
          EscapeJsonPointer(input.logical_name);
      auto port_it = node.ports.inputs.find(input.logical_name);
      if (port_it == node.ports.inputs.end()) {
        if (input.required) {
          Add(&report, DiagnosticCode::kMissingInputProducer, input_path,
              "Required input port must be explicitly connected: " +
                  input.logical_name,
              id, input.logical_name);
        }
        continue;
      }
      const std::string& actual_key = port_it->second;
      bound_input_ports.insert(input.logical_name);
      node_plan.ports.push_back({input.logical_name, actual_key, input.type_id,
                                 input.cardinality, input.provenance_policy,
                                 input.lifetime, PortDirection::kInput});
      bool found = false;
      std::string source_id;
      const PortContract* source_contract = nullptr;
      auto producer_it = producers.find(actual_key);
      if (producer_it != producers.end() && producer_it->second.size() == 1 &&
          !ingress.count(actual_key)) {
        const auto& producer = producer_it->second.front();
        if (producer.second.type_id == input.type_id) {
          found = true;
          source_id = producer.first;
          source_contract = &producer.second;
          ValidatePortFlowContract(producer.second, input, input_path,
                                   producer.first, id, PortDirection::kInput,
                                   input.logical_name, actual_key, &report);
        }
      } else if (producer_it == producers.end()) {
        auto root_port = ingress.find(actual_key);
        if (root_port != ingress.end() &&
            root_port->second.type_id == input.type_id) {
          found = true;
          source_id = "$ingress";
          source_contract = &root_port->second;
          ValidatePortFlowContract(root_port->second, input, input_path,
                                   "$ingress", id, PortDirection::kInput,
                                   input.logical_name, actual_key, &report);
        }
      }
      if (input.cardinality == "1:1") {
        const KeyShape shape =
            found ? shape_of(actual_key) : KeyShape::Unknown();
        if (item_shape_port.empty()) {
          item_shape = shape;
          item_shape_port = input.logical_name;
          item_shape_key = actual_key;
        } else if (item_shape.Known() && shape.Known() &&
                   !(item_shape == shape)) {
          AddPortFlowDiagnostic(
              &report, DiagnosticCode::kPortCardinalityMismatch, input_path,
              "Port cardinality mismatch: item-wise input '" +
                  input.logical_name + "' receives " + DescribeShape(shape) +
                  ", but item-wise input '" + item_shape_port + "' receives " +
                  DescribeShape(item_shape) +
                  "; item-wise inputs must pair item by item",
              source_id, id, PortDirection::kInput, input.logical_name,
              actual_key, *source_contract, input);
          auto& facts = report.diagnostics.back().facts;
          facts["actual_shape"] = ShapeFacts(shape);
          facts["expected_shape"] = ShapeFacts(item_shape);
          facts["anchor_port"] = item_shape_port;
          facts["anchor_key"] = item_shape_key;
          item_shape = KeyShape::Unknown();
        } else if (!shape.Known()) {
          item_shape = KeyShape::Unknown();
        }
      }
      if (!found && biz && !has_only_unresolved_source(actual_key)) {
        std::vector<std::string> suggestions;
        for (const auto& candidate : catalog.nodes) {
          if (std::any_of(candidate.outputs.begin(), candidate.outputs.end(),
                          [&](const auto& output) {
                            return output.type_id == input.type_id;
                          })) {
            suggestions.push_back(candidate.node_type);
          }
        }
        Add(&report, DiagnosticCode::kMissingInputProducer, input_path,
            "No unique compatible biz ingress or node produces port '" +
                input.logical_name + "' (bound key: '" + actual_key +
                "') of type '" + input.type_id + "'",
            id, input.logical_name, {}, suggestions);
      }
    }

    // 校验端口组合约束 (Port Group Constraints)
    for (const auto& constraint : definition.port_constraints) {
      bool satisfied = true;
      if (constraint.kind == PortConstraintKind::kExactOneGroupOf) {
        int fully_matched_groups = 0;
        for (size_t g = 0; g < constraint.port_groups.size(); ++g) {
          const auto& group = constraint.port_groups[g];
          bool all_in = true;
          for (const auto& p : group) {
            if (!bound_input_ports.count(p)) {
              all_in = false;
              break;
            }
          }
          if (all_in) {
            bool only_this_group = true;
            for (const auto& p : bound_input_ports) {
              if (std::find(group.begin(), group.end(), p) == group.end()) {
                for (size_t og = 0; og < constraint.port_groups.size(); ++og) {
                  if (og != g) {
                    if (std::find(constraint.port_groups[og].begin(),
                                  constraint.port_groups[og].end(),
                                  p) != constraint.port_groups[og].end()) {
                      only_this_group = false;
                      break;
                    }
                  }
                }
              }
              if (!only_this_group) break;
            }
            if (only_this_group) {
              fully_matched_groups++;
            }
          }
        }
        satisfied = (fully_matched_groups == 1);
      } else {
        size_t count = 0;
        for (const auto& p : constraint.ports) {
          if (bound_input_ports.count(p)) {
            count++;
          }
        }
        switch (constraint.kind) {
          case PortConstraintKind::kAtLeastOneOf:
            satisfied = (count >= 1);
            break;
          case PortConstraintKind::kExactlyOneOf:
            satisfied = (count == 1);
            break;
          case PortConstraintKind::kAllOrNone:
            satisfied = (count == 0 || count == constraint.ports.size());
            break;
          case PortConstraintKind::kAtMostOneOf:
            satisfied = (count <= 1);
            break;
          case PortConstraintKind::kExactOneGroupOf:
            break;
        }
      }
      if (!satisfied) {
        std::string msg = constraint.message.empty()
                              ? ("Port constraint violation for node '" +
                                 definition.node_type + "'")
                              : constraint.message;
        Add(&report, DiagnosticCode::kInvalidCombination,
            "/pipeline/" + std::to_string(node.source_index), msg, id);
      }
    }

    for (const auto& declared_output : definition.outputs) {
      const auto output = EffectivePortDefinition(declared_output, definition,
                                                  normalized_config);
      std::string actual_key = output.logical_name;
      auto port_it = node.ports.outputs.find(output.logical_name);
      if (port_it != node.ports.outputs.end()) {
        actual_key = port_it->second;
      }

      node_plan.ports.push_back(
          {output.logical_name, actual_key, output.type_id, output.cardinality,
           output.provenance_policy, output.lifetime, PortDirection::kOutput});
      key_shapes[actual_key] =
          NodeOutputShape(output, item_shape, id + "." + output.logical_name);
    }

    plan.node_plans[id] = std::move(node_plan);
  }

  if (biz) {
    for (const auto& consumer : biz->egress) {
      auto it = producers.find(consumer.blackboard_key);
      if (it == producers.end() || it->second.empty()) {
        if (consumer.required &&
            !has_only_unresolved_source(consumer.blackboard_key)) {
          Add(&report, DiagnosticCode::kMissingBizOutput, "/pipeline",
              "Pipeline does not produce required biz output: " +
                  consumer.blackboard_key,
              {}, consumer.blackboard_key);
          reported_missing_outputs.insert(consumer.blackboard_key);
        }
        continue;
      }
      const auto& [producer_id, producer_port] = it->second.back();
      const auto& producer_node = *node_by_id.at(producer_id);
      std::string output_path =
          "/pipeline/" + std::to_string(producer_node.source_index);
      for (const auto& [logical_key, actual_key] :
           producer_node.ports.outputs) {
        if (actual_key == consumer.blackboard_key) {
          output_path += "/outputs/" + logical_key;
          break;
        }
      }
      if (producer_port.type_id != consumer.type_id) {
        Add(&report, DiagnosticCode::kMissingBizOutput, output_path,
            "Biz output type mismatch for '" + consumer.blackboard_key +
                "': expected '" + consumer.type_id + "', got '" +
                producer_port.type_id + "'",
            producer_id, consumer.blackboard_key, {"$egress"});
        continue;
      }
      ValidatePortFlowContract(producer_port, consumer, output_path,
                               producer_id, "$egress", PortDirection::kOutput,
                               consumer.blackboard_key, consumer.blackboard_key,
                               &report);
      ValidateBoundaryShape(shape_of(consumer.blackboard_key), producer_port,
                            consumer, output_path, producer_id, "$egress",
                            consumer.blackboard_key, &report);
    }
  }

  if (io_boundary) {
    for (const auto& consumer : io_boundary->output_consumed_ports) {
      auto it = producers.find(consumer.blackboard_key);
      if (it == producers.end() || it->second.empty()) {
        auto ing_it = ingress.find(consumer.blackboard_key);
        if (ing_it != ingress.end()) {
          if (ing_it->second.type_id != consumer.type_id) {
            Add(&report, DiagnosticCode::kMissingBizOutput, "/io/output",
                "IO boundary output type mismatch for '" +
                    consumer.blackboard_key + "': expected '" +
                    consumer.type_id + "', got '" + ing_it->second.type_id +
                    "'",
                "$ingress", consumer.blackboard_key, {"$io_output"});
          } else {
            ValidatePortFlowContract(
                ing_it->second, consumer, "/io/output", "$ingress",
                "$io_output", PortDirection::kOutput, consumer.blackboard_key,
                consumer.blackboard_key, &report);
            ValidateBoundaryShape(shape_of(consumer.blackboard_key),
                                  ing_it->second, consumer, "/io/output",
                                  "$ingress", "$io_output",
                                  consumer.blackboard_key, &report);
          }
          continue;
        }
        if (consumer.required &&
            !has_only_unresolved_source(consumer.blackboard_key) &&
            !reported_missing_outputs.count(consumer.blackboard_key)) {
          Add(&report, DiagnosticCode::kMissingBizOutput, "/io/output",
              "Pipeline does not produce required IO boundary output: " +
                  consumer.blackboard_key,
              {}, consumer.blackboard_key);
        }
        continue;
      }
      const auto& [producer_id, producer_port] = it->second.back();
      if (producer_port.type_id != consumer.type_id) {
        Add(&report, DiagnosticCode::kMissingBizOutput, "/io/output",
            "IO boundary output type mismatch for '" + consumer.blackboard_key +
                "': expected '" + consumer.type_id + "', got '" +
                producer_port.type_id + "'",
            producer_id, consumer.blackboard_key, {"$io_output"});
        continue;
      }
      ValidatePortFlowContract(producer_port, consumer, "/io/output",
                               producer_id, "$io_output",
                               PortDirection::kOutput, consumer.blackboard_key,
                               consumer.blackboard_key, &report);
      ValidateBoundaryShape(shape_of(consumer.blackboard_key), producer_port,
                            consumer, "/io/output", producer_id, "$io_output",
                            consumer.blackboard_key, &report);
    }
  }

  if (parsed.max_parallel_workers > 1) {
    // 将非线程安全 Node 和共享串行模型的使用者拆分到各自的层。
    // 写冲突仍按原始层检查。
    auto serialized_models = [&](const std::string& id) {
      std::unordered_set<std::string> models;
      for (const auto& binding : plan.node_plans[id].model_bindings) {
        if (binding.model_id.empty()) continue;
        auto it = model_concurrency.find(binding.model_id);
        if (it != model_concurrency.end() &&
            it->second == InferenceConcurrency::kSerialized) {
          models.insert(binding.model_id);
        }
      }
      return models;
    };
    std::vector<std::vector<std::string>> scheduled;
    for (const auto& layer : report.topological_layers) {
      std::unordered_map<std::string, std::string> writes;
      std::vector<std::string> parallel;
      std::vector<std::string> sequential;
      std::unordered_set<std::string> used_models;
      for (const auto& id : layer) {
        auto def_it = def_by_id.find(id);
        if (def_it == def_by_id.end() || !def_it->second->parallel_safe) {
          sequential.push_back(id);
        } else {
          auto models = serialized_models(id);
          const bool shares = std::any_of(models.begin(), models.end(),
                                          [&](const std::string& model) {
                                            return used_models.count(model) > 0;
                                          });
          if (shares) {
            sequential.push_back(id);
          } else {
            used_models.insert(models.begin(), models.end());
            parallel.push_back(id);
          }
        }
        if (def_it == def_by_id.end()) continue;
        const auto& node_plan = plan.node_plans[id];
        for (const auto& p : node_plan.ports) {
          if (p.direction != PortDirection::kOutput) continue;
          auto inserted = writes.emplace(p.blackboard_key, id);
          if (!inserted.second) {
            Add(&report, DiagnosticCode::kParallelWriteConflict, "/pipeline",
                "Parallel layer writes the same port: " + p.blackboard_key, id,
                p.logical_name, {inserted.first->second});
          }
        }
      }
      if (!parallel.empty()) scheduled.push_back(std::move(parallel));
      for (auto& id : sequential) scheduled.push_back({std::move(id)});
    }
    report.topological_layers = std::move(scheduled);
    report.topological_order.clear();
    for (const auto& layer : report.topological_layers) {
      report.topological_order.insert(report.topological_order.end(),
                                      layer.begin(), layer.end());
    }
  }

  finish_plan(plan);
  return plan;
}

}  // namespace

nlohmann::json ValidationFix::ToJson() const {
  return {{"id", id},
          {"title", title},
          {"effect", effect},
          {"patch", patch},
          {"verification", verification}};
}

nlohmann::json ValidationRemediation::ToJson() const {
  nlohmann::json fixes_json = nlohmann::json::array();
  for (const auto& fix : fixes) {
    fixes_json.push_back(fix.ToJson());
  }
  return {{"schema_version", schema_version},
          {"cause", RemediationCauseName(cause)},
          {"summary", summary},
          {"facts", facts},
          {"fixes", std::move(fixes_json)}};
}

nlohmann::json ValidationDiagnostic::ToJson() const {
  nlohmann::json item = {{"code", DiagnosticCodeName(code)},
                         {"path", path},
                         {"message", message},
                         {"severity", severity}};
  if (!node_id.empty()) item["node_id"] = node_id;
  if (!port.empty()) item["port"] = port;
  if (!related_nodes.empty()) item["related_nodes"] = related_nodes;
  if (!suggestions.empty()) item["suggestions"] = suggestions;
  if (!facts.empty()) item["facts"] = facts;
  if (remediation.has_value()) {
    item["remediation"] = remediation->ToJson();
  }
  return item;
}

nlohmann::json ValidationReport::ToJson() const {
  nlohmann::json items = nlohmann::json::array();
  for (const auto& diagnostic : diagnostics) {
    items.push_back(diagnostic.ToJson());
  }
  return {{"schema_version", 1},
          {"ok", ok},
          {"diagnostics", std::move(items)},
          {"plan",
           {{"topological_order", topological_order},
            {"layers", topological_layers}}}};
}

ValidatedPipelinePlan PipelineValidator::ValidateAndPlan(
    const nlohmann::json& root, const PipelineIoBoundary* io_boundary) {
  const auto catalog = PipelineCatalog::Snapshot();
  return ValidateAndPlanInternal(root, catalog, io_boundary);
}

ValidationReport PipelineValidator::Validate(
    const nlohmann::json& root, const PipelineIoBoundary* io_boundary) {
  return ValidateAndPlan(root, io_boundary).report;
}

}  // namespace llm_edgeflow
