#include "core/pipeline_validator.h"

#include <algorithm>
#include <functional>
#include <queue>
#include <set>
#include <unordered_map>
#include <unordered_set>

#include "contracts/config_schema_validation.h"
#include "contracts/json_pointer.h"
#include "core/node_registry.h"
#include "core/pipeline_catalog.h"
#include "core/pipeline_config.h"
#include "engine/backend_registry.h"
#include "engine/model_registry.h"
#include "name_suggestions.h"
#include "pipeline_config_structure.h"

namespace llm_edgeflow {
namespace {

void Add(ValidationReport* report, DiagnosticCode code, std::string path,
         std::string message, std::string node_name = {}, std::string port = {},
         std::vector<std::string> related = {},
         std::vector<std::string> suggestions = {}) {
  report->diagnostics.push_back({code, std::move(path), std::move(message),
                                 "error", std::move(node_name), std::move(port),
                                 std::move(related), std::move(suggestions),
                                 nlohmann::json::object()});
}

nlohmann::json PortContractFacts(const PortContract& port) {
  return {{"type_id", port.type_id},
          {"cardinality", port.cardinality},
          {"provenance_policy", port.provenance_policy},
          {"lifetime", port.lifetime}};
}

void AddPortFlowDiagnostic(
    ValidationReport* report, DiagnosticCode code, const std::string& path,
    std::string message, const std::string& producer_name,
    const std::string& consumer_name, PortDirection location,
    const std::string& logical_port, const std::string& bound_key,
    const PortContract& producer, const PortContract& consumer) {
  // Node 输入诊断归属消费者，边界诊断归属生产者。
  // 保留这些位置和相关 Node ID。
  const bool boundary = location == PortDirection::kOutput;
  Add(report, code, path, std::move(message),
      boundary ? producer_name : consumer_name, logical_port,
      {boundary ? consumer_name : producer_name});
  report->diagnostics.back().facts = {
      {"producer_name", producer_name},
      {"consumer_name", consumer_name},
      {"bound_key", bound_key},
      {"actual", PortContractFacts(producer)},
      {"expected", PortContractFacts(consumer)}};
}

// 一个请求在某 Blackboard 键下的条目数。Node 的 cardinality 描述 Node 自身的
// 关系：输入表示条目的消费方式 ("1:1" 逐条，"N:1" 按请求分组，"N:M" 任意)，
// 且接受任意形状；输出表示产出条目与逐条输入之间的关系。形状沿 DAG 推导，
// 只在关键处检查：要求每请求一个条目的边界，以及必须两两配对的逐条输入。
struct KeyShape {
  enum class Kind { kUnknown, kPerRequest, kMulti };
  Kind kind = Kind::kUnknown;
  std::string origin;  // 生成 kMulti 形状条目的扇出来源。

  static KeyShape Unknown() { return {}; }
  static KeyShape PerRequest() { return {Kind::kPerRequest, {}}; }
  static KeyShape Multi(std::string origin) {
    return {Kind::kMulti, std::move(origin)};
  }
  bool Known() const { return kind != Kind::kUnknown; }
  bool operator==(const KeyShape& other) const {
    return kind == other.kind && origin == other.origin;
  }
};

std::string DescribeShape(const KeyShape& shape) {
  switch (shape.kind) {
    case KeyShape::Kind::kPerRequest:
      return "one item per request";
    case KeyShape::Kind::kMulti:
      return "zero or more items per request generated by '" + shape.origin +
             "'";
    case KeyShape::Kind::kUnknown:
      break;
  }
  return "an unknown number of items per request";
}

nlohmann::json ShapeFacts(const KeyShape& shape) {
  switch (shape.kind) {
    case KeyShape::Kind::kPerRequest:
      return {{"kind", "per_request"}};
    case KeyShape::Kind::kMulti:
      return {{"kind", "multi"}, {"origin", shape.origin}};
    case KeyShape::Kind::kUnknown:
      break;
  }
  return {{"kind", "unknown"}};
}

// IO 边界端口按请求计数："1:1" 恰为一个条目，
// 其他声明均为归属该请求的集合。
KeyShape BoundaryShape(const PortContract& port, std::string origin) {
  return port.cardinality == "1:1" ? KeyShape::PerRequest()
                                   : KeyShape::Multi(std::move(origin));
}

KeyShape NodeOutputShape(const PortContract& output, const KeyShape& item_shape,
                         std::string origin) {
  if (output.cardinality == "1:1") return item_shape;
  if (output.cardinality == "1:N") return KeyShape::Multi(std::move(origin));
  if (output.cardinality == "N:1") return KeyShape::PerRequest();
  return KeyShape::Unknown();
}

void ValidateBoundaryShape(
    const KeyShape& produced, const PortContract& producer,
    const IoPortDefinition& consumer, const std::string& path,
    const std::string& producer_name, const std::string& consumer_name,
    const std::string& bound_key, ValidationReport* report) {
  if (consumer.cardinality != "1:1" || produced.kind != KeyShape::Kind::kMulti)
    return;
  AddPortFlowDiagnostic(report, DiagnosticCode::kPortCardinalityMismatch, path,
                        "Port cardinality mismatch: '" + bound_key +
                            "' requires one item per request but receives " +
                            DescribeShape(produced),
                        producer_name, consumer_name, PortDirection::kOutput,
                        consumer.logical_name, bound_key, producer, consumer);
  auto& facts = report->diagnostics.back().facts;
  facts["actual_shape"] = ShapeFacts(produced);
  facts["expected_shape"] = ShapeFacts(KeyShape::PerRequest());
}

bool ProvenanceCompatible(const std::string& producer,
                          const std::string& consumer) {
  if (consumer == "preserve" || consumer == "aggregate") return true;
  return producer == consumer;
}

int LifetimeRank(const std::string& lifetime) {
  if (lifetime == "request") return 0;
  if (lifetime == "session") return 1;
  return -1;
}

bool LifetimeCompatible(const std::string& producer,
                        const std::string& consumer) {
  return LifetimeRank(producer) >= LifetimeRank(consumer);
}

void ValidatePortFlowContract(
    const PortContract& producer, const PortContract& consumer,
    const std::string& path, const std::string& producer_name,
    const std::string& consumer_name, PortDirection location,
    const std::string& logical_port, const std::string& bound_key,
    ValidationReport* report) {
  if (!ProvenanceCompatible(producer.provenance_policy,
                            consumer.provenance_policy)) {
    AddPortFlowDiagnostic(report, DiagnosticCode::kPortProvenanceMismatch, path,
                          "Port provenance mismatch: producer policy '" +
                              producer.provenance_policy +
                              "' cannot satisfy consumer policy '" +
                              consumer.provenance_policy + "'",
                          producer_name, consumer_name, location, logical_port,
                          bound_key, producer, consumer);
  }
  if (!LifetimeCompatible(producer.lifetime, consumer.lifetime)) {
    AddPortFlowDiagnostic(
        report, DiagnosticCode::kPortLifetimeMismatch, path,
        "Port lifetime mismatch: producer lifetime '" + producer.lifetime +
            "' is shorter than consumer lifetime '" + consumer.lifetime + "'",
        producer_name, consumer_name, location, logical_port, bound_key,
        producer, consumer);
  }
}

}  // namespace

bool ValidateAndNormalizeConfig(
    const std::vector<ConfigFieldDefinition>& schema,
    const nlohmann::json& input, nlohmann::json* normalized,
    std::vector<ValidationDiagnostic>* diagnostics,
    const std::string& base_pointer) {
  std::vector<ConfigFieldValidationError> field_errors;
  bool ok =
      ValidateAndNormalizeFields(schema, input, normalized, &field_errors);
  if (!ok && diagnostics) {
    for (const auto& err : field_errors) {
      ValidationDiagnostic diag;
      diag.path = err.kind == ConfigFieldErrorKind::kNotAnObject
                      ? base_pointer
                      : base_pointer + err.path;
      diag.message = err.message;
      switch (err.kind) {
        case ConfigFieldErrorKind::kNotAnObject:
          diag.code = DiagnosticCode::kConfigFieldType;
          break;
        case ConfigFieldErrorKind::kUnknownField: {
          diag.code = DiagnosticCode::kUnknownConfigField;
          const nlohmann::json::json_pointer pointer(err.path);
          if (const auto* fields =
                  FindConfigObjectFields(schema, pointer.parent_pointer())) {
            for (const auto& field : *fields)
              diag.suggestions.push_back(field.name);
          }
          diag.suggestions =
              RankByEditDistance(pointer.back(), std::move(diag.suggestions));
          break;
        }
        case ConfigFieldErrorKind::kMissingField:
          diag.code = DiagnosticCode::kMissingConfigField;
          break;
        case ConfigFieldErrorKind::kTypeMismatch:
          diag.code = DiagnosticCode::kConfigFieldType;
          break;
        case ConfigFieldErrorKind::kOutOfRange:
        case ConfigFieldErrorKind::kNonFinite:
          diag.code = DiagnosticCode::kConfigFieldRange;
          break;
        case ConfigFieldErrorKind::kInvalidEnum:
          diag.code = DiagnosticCode::kConfigFieldEnum;
          break;
      }
      diag.severity = "error";
      diagnostics->push_back(std::move(diag));
    }
  }
  return ok;
}

namespace {

nlohmann::json ValidateConfigFields(
    const std::vector<ConfigFieldDefinition>& definitions,
    const nlohmann::json& config, const std::string& path_prefix,
    const std::string& subject_id, ValidationReport* report,
    bool* out_valid = nullptr) {
  std::vector<ValidationDiagnostic> diags;
  nlohmann::json normalized = nlohmann::json::object();
  if (config.is_object()) {
    for (const auto& field : definitions) {
      if (config.contains(field.name)) {
        normalized[field.name] = config[field.name];
      } else if (!field.default_value.is_null()) {
        normalized[field.name] = field.default_value;
      }
    }
  }

  nlohmann::json validated;
  bool ok = ValidateAndNormalizeConfig(definitions, config, &validated, &diags,
                                       path_prefix);
  if (ok) {
    normalized = std::move(validated);
  }
  if (out_valid) *out_valid = ok;
  for (auto& d : diags) {
    d.node_name = subject_id;
    report->diagnostics.push_back(std::move(d));
  }
  return normalized;
}

bool ResolveTopology(const std::vector<ParsedNodeConfig>& nodes,
                     ValidationReport* report) {
  const bool unique_dependencies = PipelineConfigStructure()
                                       .at("properties")
                                       .at("pipeline")
                                       .at("items")
                                       .at("properties")
                                       .at("depends_on")
                                       .at("uniqueItems")
                                       .get<bool>();
  std::unordered_map<std::string, size_t> index;
  std::unordered_map<std::string, int> degrees;
  std::unordered_map<std::string, std::vector<std::string>> children;
  for (size_t i = 0; i < nodes.size(); ++i) {
    index[nodes[i].name] = i;
    degrees[nodes[i].name] = 0;
  }
  bool invalid_reference = false;
  for (const auto& node : nodes) {
    std::unordered_set<std::string> seen;
    for (size_t d = 0; d < node.depends_on.size(); ++d) {
      const auto& dep = node.depends_on[d];
      std::string path = "/pipeline/" + std::to_string(node.source_index) +
                         "/depends_on/" + std::to_string(d);
      if (dep == node.name) {
        Add(report, DiagnosticCode::kDagCycle, path,
            "Node cannot depend on itself", node.name, {}, {dep});
        invalid_reference = true;
      } else if (index.find(dep) == index.end()) {
        Add(report, DiagnosticCode::kInvalidDependency, path,
            "Dependency references an unknown node: " + dep, node.name, {},
            {dep});
        invalid_reference = true;
      } else if (unique_dependencies && !seen.insert(dep).second) {
        Add(report, DiagnosticCode::kDuplicateDependency, path,
            "Dependency is declared more than once: " + dep, node.name, {},
            {dep});
        invalid_reference = true;
      } else {
        ++degrees[node.name];
        children[dep].push_back(node.name);
      }
    }
  }
  std::vector<std::string> current;
  for (const auto& node : nodes) {
    if (degrees[node.name] == 0) current.push_back(node.name);
  }
  size_t resolved = 0;
  while (!current.empty()) {
    report->topological_layers.push_back(current);
    std::vector<std::string> next;
    for (const auto& id : current) {
      report->topological_order.push_back(id);
      ++resolved;
      for (const auto& child : children[id]) {
        if (--degrees[child] == 0) next.push_back(child);
      }
    }
    current = std::move(next);
  }
  if (resolved != nodes.size()) {
    Add(report, DiagnosticCode::kDagCycle, "/pipeline",
        "Cyclic dependency detected in pipeline");
    return false;
  }
  return !invalid_reference;
}

ValidatedPipelinePlan ValidateAndPlanInternal(
    ParsedPipelineConfig config, const PipelineCatalogSnapshot& catalog,
    const PipelineIoBoundary& io_boundary) {
  ValidatedPipelinePlan plan;
  plan.config = std::move(config);
  ValidationReport& report = plan.report;

  auto finish_plan = [&](ValidatedPipelinePlan& p) {
    p.report.ok = p.report.diagnostics.empty();
  };

  const auto& parsed = plan.config;
  if (catalog.node_registry_has_conflict) {
    std::string message = "Node registry contains registration conflicts";
    for (const auto& error : catalog.node_registry_errors) {
      message += ": " + error;
    }
    Add(&report, DiagnosticCode::kRegistryConflict, "/pipeline",
        std::move(message));
  }
  if (ModelRegistry::Instance().HasConflict()) {
    std::string message = "Model registry contains registration conflicts";
    for (const auto& error : ModelRegistry::Instance().GetConflictErrors()) {
      message += ": " + error;
    }
    Add(&report, DiagnosticCode::kRegistryConflict, "/models",
        std::move(message));
  }
  if (BackendRegistry::Instance().HasConflict()) {
    std::string message = "Backend registry contains registration conflicts";
    for (const auto& error : BackendRegistry::Instance().GetConflictErrors()) {
      message += ": " + error;
    }
    Add(&report, DiagnosticCode::kRegistryConflict, "/models",
        std::move(message));
  }

  std::unordered_set<std::string> unresolved_model_names;
  std::unordered_map<std::string, std::string> model_types;
  std::unordered_map<std::string, InferenceConcurrency> model_concurrency;
  const auto& model_registry = ModelRegistry::Instance();
  std::set<std::string> registered_model_types;
  for (const auto& definition : model_registry.ListDefinitions())
    registered_model_types.insert(definition.model_type);
  for (const auto& model : parsed.models) {
    const auto at = "/models/" + std::to_string(model.source_index);
    if (!registered_model_types.count(model.model_type)) {
      unresolved_model_names.insert(model.model_name);
      Add(&report, DiagnosticCode::kUnknownModelType, at + "/type",
          "Unknown model type: " + model.model_type, {}, {}, {},
          RankByEditDistance(model.model_type, {registered_model_types.begin(),
                                                registered_model_types.end()}));
      continue;
    }
    // Record the requested category even if its backend cannot be selected.
    model_types[model.model_name] = model.model_type;
    std::vector<std::string> compatible_backends;
    for (const auto& backend : BackendRegistry::Instance().ListDefinitions())
      if (!model_registry
               .FindImplementation(model.model_type, backend.backend_type)
               .empty())
        compatible_backends.push_back(backend.backend_type);
    auto backend = BackendRegistry::Instance().Find(model.backend_type);
    if (!backend) {
      Add(&report, DiagnosticCode::kUnknownBackend, at + "/backend/type",
          "Unknown backend: " + model.backend_type, {}, {}, {},
          RankByEditDistance(model.backend_type,
                             std::move(compatible_backends)));
      continue;
    }
    const auto selected =
        model_registry.FindImplementation(model.model_type, model.backend_type);
    if (selected.empty()) {
      Add(&report, DiagnosticCode::kBackendProtocolMismatch,
          at + "/backend/type",
          "No implementation for " + model.model_type + "/" +
              model.backend_type,
          {}, {}, {}, std::move(compatible_backends));
      continue;
    }
    if (selected.size() > 1) {
      std::string message = "Multiple implementations for " + model.model_type +
                            "/" + model.backend_type + ":";
      for (const auto& definition : selected)
        message += " " + definition.impl_name;
      Add(&report, DiagnosticCode::kRegistryConflict, at + "/backend/type",
          std::move(message));
      continue;
    }
    const auto& implementation = selected.front();
    const auto parse_params =
        [&](const ParameterSet& declaration, const nlohmann::json& input,
            const std::string& path, nlohmann::json* normalized) {
          std::vector<ValidationDiagnostic> errors;
          const bool valid = ValidateAndNormalizeConfig(
              declaration.Fields(), input, normalized, &errors, path);
          for (auto& diagnostic : errors)
            report.diagnostics.push_back(std::move(diagnostic));
          if (valid) {
            std::shared_ptr<const ParameterValues> values;
            std::string error;
            if (!declaration.Parse(*normalized, &values, &error))
              Add(&report, DiagnosticCode::kInvalidCombination, path,
                  error.empty() ? "Invalid parameter combination" : error);
          }
        };
    ValidatedModelPlan model_plan;
    model_plan.model_name = model.model_name;
    model_plan.model_type = model.model_type;
    model_plan.impl_name = implementation.impl_name;
    model_plan.backend_type = model.backend_type;
    model_plan.model_file = model.model_file;
    parse_params(implementation.params, model.model_params, at + "/params",
                 &model_plan.model_params);
    parse_params(backend->params, model.backend_params, at + "/backend/params",
                 &model_plan.backend_params);
    model_plan.protocol = implementation.required_protocol;
    model_plan.effective_concurrency =
        implementation.concurrency == InferenceConcurrency::kSerialized ||
                backend->concurrency == InferenceConcurrency::kSerialized
            ? InferenceConcurrency::kSerialized
            : InferenceConcurrency::kConcurrent;
    model_concurrency[model.model_name] = model_plan.effective_concurrency;
    model_plan.source_index = model.source_index;
    plan.models.push_back(std::move(model_plan));
  }

  std::unordered_set<std::string> used_models;
  bool has_unknown_nodes = false;
  const auto& nodes = parsed.nodes;
  std::unordered_map<std::string, const ParsedNodeConfig*> node_by_name;
  std::unordered_map<std::string, const NodeDefinition*> def_by_name;
  std::unordered_map<std::string, nlohmann::json> normalized_params_by_node;
  std::unordered_set<std::string> valid_node_fields;
  for (const auto& node : nodes) {
    node_by_name[node.name] = &node;
    const auto* definition = catalog.FindNode(node.node_type);
    if (!definition) {
      has_unknown_nodes = true;
      std::vector<std::string> node_types;
      for (const auto& def : catalog.nodes) node_types.push_back(def.node_type);
      Add(&report, DiagnosticCode::kUnknownNodeType,
          "/pipeline/" + std::to_string(node.source_index) + "/type",
          "Unknown node_type or missing catalog definition: " + node.node_type,
          node.name, {}, {},
          NearestNames(node.node_type, std::move(node_types)));
      continue;
    }
    def_by_name[node.name] = definition;

    bool node_fields_valid = false;
    auto normalized_params = ValidateConfigFields(
        definition->config_fields, node.params,
        "/pipeline/" + std::to_string(node.source_index) + "/params", node.name,
        &report, &node_fields_valid);
    if (node_fields_valid) valid_node_fields.insert(node.name);
    normalized_params_by_node[node.name] = normalized_params;

    for (const auto& dep : definition->model_dependencies) {
      std::string model_name;
      if (normalized_params.contains(dep.config_field) &&
          normalized_params[dep.config_field].is_string()) {
        model_name = normalized_params[dep.config_field].get<std::string>();
      }
      if (!model_name.empty()) used_models.insert(model_name);
      auto model_type = model_types.find(model_name);
      std::string path = "/pipeline/" + std::to_string(node.source_index) +
                         "/params/" + EscapeJsonPointer(dep.config_field);
      if (model_name.empty() || model_type == model_types.end()) {
        if (!unresolved_model_names.count(model_name)) {
          Add(&report, DiagnosticCode::kUnknownModelReference, path,
              "Node references an unknown model_name: " + model_name,
              node.name);
        }
      } else if (model_type->second != dep.model_type) {
        Add(&report, DiagnosticCode::kModelTypeMismatch, path,
            "Node requires model type '" + dep.model_type +
                "' but model provides '" + model_type->second + "'",
            node.name);
      }
    }
  }

  if (!has_unknown_nodes) {
    for (const auto& model : parsed.models)
      if (!used_models.count(model.model_name))
        Add(&report, DiagnosticCode::kUnusedModel,
            "/models/" + std::to_string(model.source_index) + "/name",
            "Model is not bound by any node: " + model.model_name);
  }

  std::unordered_map<std::string, IoPortDefinition> ingress;
  for (const auto& port : io_boundary.input_published_ports) {
    if (!ingress.emplace(port.blackboard_key, port).second) {
      Add(&report, DiagnosticCode::kDuplicatePortProducer, "/io/input",
          "Input items publish the same logical port: " + port.blackboard_key,
          "input", port.blackboard_key);
    }
  }
  using Producer = std::pair<std::string, PortContract>;
  std::unordered_map<std::string, Producer> producers;
  for (const auto& node : nodes) {
    const auto it = def_by_name.find(node.name);
    if (it == def_by_name.end()) continue;
    for (const auto& output : it->second->outputs)
      producers.emplace(node.name + "." + output.logical_name,
                        Producer{node.name, output});
  }
  std::unordered_set<std::string> referenced_keys;
  const auto source_contract =
      [&](const std::string& key) -> const PortContract* {
    const auto input = ingress.find(key);
    if (input != ingress.end()) return &input->second;
    const auto node = producers.find(key);
    return node == producers.end() ? nullptr : &node->second.second;
  };
  const auto source_name = [](const std::string& key) {
    return key.substr(0, key.find('.'));
  };
  const auto resolve_source =
      [&](const std::string& key, const std::string& path,
          const std::string& consumer,
          const std::string& port) -> const PortContract* {
    const auto dot = key.find('.');
    if (dot == std::string::npos || dot == 0 || dot + 1 == key.size() ||
        key.find('.', dot + 1) != std::string::npos) {
      Add(&report, DiagnosticCode::kFieldType, path,
          "Input source must have exactly one '.' in name.port form", consumer,
          port);
      return nullptr;
    }
    const auto name = source_name(key);
    if (name != "input" && !node_by_name.count(name)) {
      std::vector<std::string> names{"input"};
      for (const auto& node : nodes) names.push_back(node.name);
      Add(&report, DiagnosticCode::kUnknownNodeReference, path,
          "Unknown source node: " + name, consumer, port, {},
          NearestNames(name, std::move(names)));
      return nullptr;
    }
    if (name != "input" && !def_by_name.count(name)) return nullptr;
    const auto* contract = source_contract(key);
    if (!contract) {
      std::vector<std::string> ports;
      if (name == "input") {
        for (const auto& input : io_boundary.input_published_ports)
          ports.push_back(
              input.blackboard_key.substr(input.blackboard_key.find('.') + 1));
      } else {
        for (const auto& output : def_by_name.at(name)->outputs)
          ports.push_back(output.logical_name);
      }
      Add(&report, DiagnosticCode::kUnknownPortReference, path,
          "Unknown source port: " + key, consumer, port, {name},
          std::move(ports));
      return nullptr;
    }
    referenced_keys.insert(key);
    return contract;
  };
  for (auto& node : plan.config.nodes) {
    const auto def = def_by_name.find(node.name);
    if (def == def_by_name.end()) continue;
    for (const auto& [port, source] : node.ports.inputs) {
      const auto declared = std::find_if(
          def->second->inputs.begin(), def->second->inputs.end(),
          [&](const auto& input) { return input.logical_name == port; });
      if (declared == def->second->inputs.end()) {
        Add(&report, DiagnosticCode::kUnknownField,
            "/pipeline/" + std::to_string(node.source_index) + "/inputs/" +
                EscapeJsonPointer(port),
            "Unknown logical input port: " + port, node.name, port);
        continue;
      }
      if (!resolve_source(source,
                          "/pipeline/" + std::to_string(node.source_index) +
                              "/inputs/" + EscapeJsonPointer(port),
                          node.name, port))
        continue;
      const auto producer = source_name(source);
      if (producer == node.name) {
        Add(&report, DiagnosticCode::kDagCycle, "/pipeline",
            "Node input cannot consume its own output", node.name, port,
            {node.name});
        continue;
      }
      if (producer != "input" &&
          std::find(node.depends_on.begin(), node.depends_on.end(), producer) ==
              node.depends_on.end())
        node.depends_on.push_back(producer);
    }
  }
  for (const auto& consumer : io_boundary.output_consumed_ports) {
    const auto path = consumer.path.empty() ? "/io/output" : consumer.path;
    if (consumer.blackboard_key.empty() && !consumer.has_binding) {
      if (consumer.required)
        Add(&report, DiagnosticCode::kMissingOutputProducer, path,
            "Required output converter port must be connected: " +
                consumer.logical_name,
            "output", consumer.logical_name);
    } else {
      resolve_source(consumer.blackboard_key,
                     path + "/" + EscapeJsonPointer(consumer.logical_name),
                     "output", consumer.logical_name);
    }
  }
  for (const auto& input : io_boundary.input_published_ports)
    if (referenced_keys.count(input.blackboard_key))
      plan.input_ports.push_back(input);

  const size_t pre_topology_errors = report.diagnostics.size();
  ResolveTopology(nodes, &report);
  if (report.diagnostics.size() != pre_topology_errors ||
      report.topological_order.size() != nodes.size()) {
    finish_plan(plan);
    return plan;
  }

  std::unordered_map<std::string, KeyShape> key_shapes;
  for (const auto& [key, port] : ingress) {
    key_shapes[key] = BoundaryShape(port, key);
  }
  auto shape_of = [&](const std::string& key) {
    auto it = key_shapes.find(key);
    return it == key_shapes.end() ? KeyShape::Unknown() : it->second;
  };

  for (const auto& id : report.topological_order) {
    auto def_it = def_by_name.find(id);
    if (def_it == def_by_name.end()) continue;
    const auto& definition = *def_it->second;
    const auto& node = *node_by_name[id];
    const nlohmann::json& normalized_params = normalized_params_by_node.at(id);
    // 已绑定逐条输入共享的形状；没有逐条输入的 Node 每个请求只产出一个条目。
    KeyShape item_shape = KeyShape::PerRequest();
    std::string item_shape_port;
    std::string item_shape_key;

    ValidatedNodePlan node_plan;
    node_plan.node = node;
    node_plan.normalized_params = normalized_params;
    for (const auto& dep : definition.model_dependencies) {
      std::string model_name;
      if (normalized_params.contains(dep.config_field) &&
          normalized_params[dep.config_field].is_string()) {
        model_name = normalized_params[dep.config_field].get<std::string>();
      }
      ResolvedNodeModelBinding binding;
      binding.name = dep.name;
      binding.model_type = dep.model_type;
      binding.config_field = dep.config_field;
      binding.model_name = std::move(model_name);
      node_plan.model_bindings.push_back(std::move(binding));
    }

    std::unordered_set<std::string> bound_input_ports;
    for (const auto& declared_input : definition.inputs) {
      const auto& input = declared_input;
      const std::string input_path =
          "/pipeline/" + std::to_string(node.source_index) + "/inputs/" +
          EscapeJsonPointer(input.logical_name);
      auto port_it = node.ports.inputs.find(input.logical_name);
      if (port_it == node.ports.inputs.end()) {
        if (input.required) {
          Add(&report, DiagnosticCode::kMissingInputProducer,
              "/pipeline/" + std::to_string(node.source_index) + "/inputs",
              "Required input port must be explicitly connected: " +
                  input.logical_name,
              id, input.logical_name);
        }
        continue;
      }
      const std::string& actual_key = port_it->second;
      bound_input_ports.insert(input.logical_name);
      const auto* source_contract_ptr = source_contract(actual_key);
      const bool found =
          source_contract_ptr && source_contract_ptr->type_id == input.type_id;
      const auto source_id = source_name(actual_key);
      if (source_contract_ptr && !found) {
        AddPortFlowDiagnostic(
            &report, DiagnosticCode::kPortTypeMismatch, input_path,
            "Port type mismatch: source provides '" +
                source_contract_ptr->type_id + "', input requires '" +
                input.type_id + "'",
            source_id, id, PortDirection::kInput, input.logical_name,
            actual_key, *source_contract_ptr, input);
      }
      if (found) {
        node_plan.ports.push_back(
            {input.logical_name, actual_key, input.type_id, input.cardinality,
             input.provenance_policy, source_contract_ptr->lifetime,
             PortDirection::kInput});
        ValidatePortFlowContract(*source_contract_ptr, input, input_path,
                                 source_id, id, PortDirection::kInput,
                                 input.logical_name, actual_key, &report);
      }
      if (input.cardinality == "1:1") {
        const KeyShape shape =
            found ? shape_of(actual_key) : KeyShape::Unknown();
        if (item_shape_port.empty()) {
          item_shape = shape;
          item_shape_port = input.logical_name;
          item_shape_key = actual_key;
        } else if (item_shape.Known() && shape.Known() &&
                   !(item_shape == shape)) {
          AddPortFlowDiagnostic(
              &report, DiagnosticCode::kPortCardinalityMismatch, input_path,
              "Port cardinality mismatch: item-wise input '" +
                  input.logical_name + "' receives " + DescribeShape(shape) +
                  ", but item-wise input '" + item_shape_port + "' receives " +
                  DescribeShape(item_shape) +
                  "; item-wise inputs must pair item by item",
              source_id, id, PortDirection::kInput, input.logical_name,
              actual_key, *source_contract_ptr, input);
          auto& facts = report.diagnostics.back().facts;
          facts["actual_shape"] = ShapeFacts(shape);
          facts["expected_shape"] = ShapeFacts(item_shape);
          facts["anchor_port"] = item_shape_port;
          facts["anchor_key"] = item_shape_key;
          item_shape = KeyShape::Unknown();
        } else if (!shape.Known()) {
          item_shape = KeyShape::Unknown();
        }
      }
    }

    // 校验端口组合约束 (Port Group Constraints)
    for (const auto& constraint : definition.port_constraints) {
      bool satisfied = true;
      if (constraint.kind == PortConstraintKind::kExactOneGroupOf) {
        int fully_matched_groups = 0;
        for (size_t g = 0; g < constraint.port_groups.size(); ++g) {
          const auto& group = constraint.port_groups[g];
          bool all_in = true;
          for (const auto& p : group) {
            if (!bound_input_ports.count(p)) {
              all_in = false;
              break;
            }
          }
          if (all_in) {
            bool only_this_group = true;
            for (const auto& p : bound_input_ports) {
              if (std::find(group.begin(), group.end(), p) == group.end()) {
                for (size_t og = 0; og < constraint.port_groups.size(); ++og) {
                  if (og != g) {
                    if (std::find(constraint.port_groups[og].begin(),
                                  constraint.port_groups[og].end(),
                                  p) != constraint.port_groups[og].end()) {
                      only_this_group = false;
                      break;
                    }
                  }
                }
              }
              if (!only_this_group) break;
            }
            if (only_this_group) {
              fully_matched_groups++;
            }
          }
        }
        satisfied = (fully_matched_groups == 1);
      } else {
        size_t count = 0;
        for (const auto& p : constraint.ports) {
          if (bound_input_ports.count(p)) {
            count++;
          }
        }
        switch (constraint.kind) {
          case PortConstraintKind::kAtLeastOneOf:
            satisfied = (count >= 1);
            break;
          case PortConstraintKind::kExactlyOneOf:
            satisfied = (count == 1);
            break;
          case PortConstraintKind::kAllOrNone:
            satisfied = (count == 0 || count == constraint.ports.size());
            break;
          case PortConstraintKind::kAtMostOneOf:
            satisfied = (count <= 1);
            break;
          case PortConstraintKind::kExactOneGroupOf:
            break;
        }
      }
      if (!satisfied) {
        std::string msg = constraint.message.empty()
                              ? ("Port constraint violation for node '" +
                                 definition.node_type + "'")
                              : constraint.message;
        Add(&report, DiagnosticCode::kInvalidCombination,
            "/pipeline/" + std::to_string(node.source_index), msg, id);
      }
    }

    BindingFacts facts;
    facts.has_bindings = true;
    facts.connected_inputs = bound_input_ports;
    for (const auto& port : node_plan.ports)
      facts.input_lifetimes[port.logical_name] = port.lifetime;
    if (valid_node_fields.count(id) && definition.validate_config) {
      std::string diagnostic, field_path;
      const auto path =
          "/pipeline/" + std::to_string(node.source_index) + "/params";
      try {
        if (!definition.validate_config(normalized_params, facts, &diagnostic,
                                        &field_path))
          Add(&report, DiagnosticCode::kInvalidCombination, path + field_path,
              diagnostic.empty() ? "Invalid node parameters" : diagnostic, id);
      } catch (const std::exception& e) {
        Add(&report, DiagnosticCode::kInvalidCombination, path, e.what(), id);
      } catch (...) {
        Add(&report, DiagnosticCode::kInvalidCombination, path,
            "Node parameter validator threw an unknown exception", id);
      }
    }
    for (const auto& declared_output : definition.outputs) {
      auto output = declared_output;
      if (!output.lifetime_from_input.empty() &&
          !facts.InputLifetime(output.lifetime_from_input).empty())
        output.lifetime = facts.InputLifetime(output.lifetime_from_input);
      const auto actual_key = id + "." + output.logical_name;
      producers.at(actual_key).second = output;
      key_shapes[actual_key] = NodeOutputShape(output, item_shape, actual_key);
      if (referenced_keys.count(actual_key))
        node_plan.ports.push_back({output.logical_name, actual_key,
                                   output.type_id, output.cardinality,
                                   output.provenance_policy, output.lifetime,
                                   PortDirection::kOutput});
    }

    plan.node_plans[id] = std::move(node_plan);
  }

  for (const auto& consumer : io_boundary.output_consumed_ports) {
    if (consumer.blackboard_key.empty()) continue;
    const auto* producer = source_contract(consumer.blackboard_key);
    if (!producer) continue;
    const auto name = source_name(consumer.blackboard_key);
    const auto path = (consumer.path.empty() ? "/io/output" : consumer.path) +
                      "/" + EscapeJsonPointer(consumer.logical_name);
    if (producer->type_id != consumer.type_id) {
      AddPortFlowDiagnostic(
          &report, DiagnosticCode::kPortTypeMismatch, path,
          "Port type mismatch: source provides '" + producer->type_id +
              "', output converter requires '" + consumer.type_id + "'",
          name, "output", PortDirection::kOutput, consumer.logical_name,
          consumer.blackboard_key, *producer, consumer);
      continue;
    }
    ValidatePortFlowContract(*producer, consumer, path, name, "output",
                             PortDirection::kOutput, consumer.logical_name,
                             consumer.blackboard_key, &report);
    ValidateBoundaryShape(shape_of(consumer.blackboard_key), *producer,
                          consumer, path, name, "output",
                          consumer.blackboard_key, &report);
  }

  if (parsed.max_parallel_workers > 1) {
    // 将非线程安全 Node 和共享串行模型的使用者拆分到各自的层。
    auto serialized_models = [&](const std::string& id) {
      std::unordered_set<std::string> models;
      for (const auto& binding : plan.node_plans[id].model_bindings) {
        if (binding.model_name.empty()) continue;
        auto it = model_concurrency.find(binding.model_name);
        if (it != model_concurrency.end() &&
            it->second == InferenceConcurrency::kSerialized) {
          models.insert(binding.model_name);
        }
      }
      return models;
    };
    std::vector<std::vector<std::string>> scheduled;
    for (const auto& layer : report.topological_layers) {
      std::vector<std::string> parallel;
      std::vector<std::string> sequential;
      std::unordered_set<std::string> used_models;
      for (const auto& id : layer) {
        auto def_it = def_by_name.find(id);
        if (def_it == def_by_name.end() || !def_it->second->parallel_safe) {
          sequential.push_back(id);
        } else {
          auto models = serialized_models(id);
          const bool shares = std::any_of(models.begin(), models.end(),
                                          [&](const std::string& model) {
                                            return used_models.count(model) > 0;
                                          });
          if (shares) {
            sequential.push_back(id);
          } else {
            used_models.insert(models.begin(), models.end());
            parallel.push_back(id);
          }
        }
      }
      if (!parallel.empty()) scheduled.push_back(std::move(parallel));
      for (auto& id : sequential) scheduled.push_back({std::move(id)});
    }
    report.topological_layers = std::move(scheduled);
    report.topological_order.clear();
    for (const auto& layer : report.topological_layers) {
      report.topological_order.insert(report.topological_order.end(),
                                      layer.begin(), layer.end());
    }
  }

  finish_plan(plan);
  return plan;
}

}  // namespace

nlohmann::json ValidationDiagnostic::ToJson() const {
  nlohmann::json item = {{"code", DiagnosticCodeName(code)},
                         {"path", path},
                         {"message", message},
                         {"severity", severity}};
  if (!node_name.empty()) item["node_name"] = node_name;
  if (!port.empty()) item["port"] = port;
  if (!related_nodes.empty()) item["related_nodes"] = related_nodes;
  if (!suggestions.empty()) item["suggestions"] = suggestions;
  if (!facts.empty()) item["facts"] = facts;
  return item;
}

nlohmann::json ValidationReport::ToJson() const {
  nlohmann::json items = nlohmann::json::array();
  for (const auto& diagnostic : diagnostics) {
    items.push_back(diagnostic.ToJson());
  }
  return {{"ok", ok},
          {"diagnostics", std::move(items)},
          {"plan",
           {{"topological_order", topological_order},
            {"layers", topological_layers}}}};
}

ValidatedPipelinePlan PipelineValidator::ValidateAndPlan(
    const nlohmann::json& root, const PipelineIoBoundary& io_boundary) {
  ParsedPipelineConfig config;
  PipelineDiagnostic diagnostic;
  if (!ParsePipelineConfig(root, &config, &diagnostic)) {
    ValidatedPipelinePlan plan;
    Add(&plan.report, diagnostic.code, diagnostic.path, diagnostic.message);
    return plan;
  }
  return ValidateParsedAndPlan(std::move(config), io_boundary);
}

ValidatedPipelinePlan PipelineValidator::ValidateParsedAndPlan(
    ParsedPipelineConfig config, const PipelineIoBoundary& io_boundary) {
  const auto catalog = PipelineCatalog::Snapshot();
  return ValidateAndPlanInternal(std::move(config), catalog, io_boundary);
}

ValidationReport PipelineValidator::Validate(
    const nlohmann::json& root, const PipelineIoBoundary& io_boundary) {
  return ValidateAndPlan(root, io_boundary).report;
}

}  // namespace llm_edgeflow
